name: venv-roadmap
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - boto3>=1.18.21
  - fiona>=1.8.20
  - geopandas>=0.10.2
  - loguru>=0.5.3
  - osmnx>=1.1.2
  - pandas>=1.3.5
  - pydantic>=1.9.0
  - pytest>=6.2.5
  - rasterio>=1.2.10
